server:
  port: 8080

logging:
    path: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://172.16.0.10:3306/cz?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: cz@com101

mybatis:
  type-aliases-package: com.monitor.entity.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

log4j:
  logger:
    com:
      monitor:
        dao: debug

jobs:
  cron: 0 0 0 1/1 * ?
#单位：毫秒
token:
  timeout: 86400000
#  timeout: 50
